DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users
(
  id SERIAL NOT NULL PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  email VARCHAR(250) NOT NULL,
  phone VARCHAR(50) NOT NULL,
  hosts BOOLEAN NOT NULL DEFAULT FALSE,
  password VARCHAR(500) NOT NULL,
  image VARCHAR(500)
);