DROP TABLE IF EXISTS cars CASCADE;

CREATE TABLE cars
(
  id SERIAL NOT NULL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  location_id INTEGER NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
  make VARCHAR(100) NOT NULL,
  model VARCHAR(100) NOT NULL,
  doors INTEGER NOT NULL,
  colour VARCHAR(100) NOT NULL,
  transmission VARCHAR(100) NOT NULL,
  description TEXT,
  pet_friendly BOOLEAN NOT NULL,
  fuel VARCHAR NOT NULL,
  seats INTEGER NOT NULL,
  image VARCHAR(500) NOT NULL,
  sport BOOLEAN,
  truck BOOLEAN,
  van BOOLEAN,
  mini_van BOOLEAN,
  luxury BOOLEAN,
  rv BOOLEAN,
  suv BOOLEAN,
  convertible BOOLEAN,
  economy BOOLEAN,
  model_year INTEGER NOT NULL
);
