DROP TABLE IF EXISTS reviews CASCADE;

CREATE TABLE reviews
(
  id SERIAL NOT NULL PRIMARY KEY,
  reviewer_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  reviewed_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  car_id INTEGER NOT NULL REFERENCES cars(id) ON DELETE CASCADE,
  date_reviewed DATE NOT NULL DEFAULT CURRENT_DATE,
  rating INTEGER NOT NULL,
  comments TEXT
);