INSERT INTO cars (user_id, location_id, make, model, doors, colour, transmission, description, pet_friendly, fuel, seats, image, sport, truck, van, mini_van, luxury, rv, suv, convertible, economy, price, model_year)
VALUES ('1', 1,'Honda', 'Civic', 4, 'Red', 'Automatic', 'Clean, 2 years old', TRUE, 'Petrol', 5, 'https://www.thetruthaboutcars.com/wp-content/uploads/2019/11/DSC0778-610x405-1.jpg', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, 80,2019),
('4', 4, 'Toyota', 'Prius', 4, 'Blue', 'Automatic', 'Only 3 years old', TRUE, 'Hybrid', 5, 'https://www.cnet.com/a/img/Qw9xsLXsFtkIc3ORDuKWo8LsMO0=/756x425/2018/12/12/c83c169f-8474-47b4-bf64-5a89a566d3bf/2019-toyota-prius-promo.jpg', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE,120, 2020),
('2', 2, 'Mercedes', 'S Class', 4, 'Black', 'Automatic', 'Only 1 year old', FALSE, 'Petrol', 4, 'https://images.caricos.com/m/mercedes-benz/2021_mercedes-benz_s-class/images/1024x768/2021_mercedes-benz_s-class_162_1024x768.jpg', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, 200, 2021),
('1', 1, 'BMW', '7 Series', 4, 'Silver', 'Automatic', 'Clean', FALSE, 'Petrol', 5, 'https://www.motortrend.com/uploads/sites/5/2020/03/2020-BMW-7-Series-7.jpg', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, 100, 2020),
('3', 3, 'Ferrari', 'Spyder', 2, 'Red', 'Manual', 'Only 2 years old', FALSE, 'Petrol', 2, 'https://s1.1zoom.me/big0/719/Ferrari_488_Spider_Red_Cabriolet_528366_1280x853.jpg', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 70, 2018),
('4', 4, 'Porsche', '911S', 2, 'Grey', 'Manual', 'Only 5 years old', FALSE, 'Petrol', 4, 'https://press.porsche.com/download/prod/presse_pag/PressBasicData.nsf/Download?OpenAgent&attachmentid=1495263&show=1', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 160, 2021),
('3', 3, 'Ford', 'F150', 4, 'White', 'Automatic', '4 years old', TRUE, 'Petrol', 5, 'https://dealerimages.dealereprocess.com/image/upload/1746586.jpg', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 150, 2020),
('2', 2, 'Dodge', 'RAM 1500', 4, 'Black', 'Automatic', '8 years old', TRUE, 'Diesel', 5, 'https://i.ytimg.com/vi/X0wOU0F22yE/maxresdefault.jpg', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 80, 2019),
('1', 1, 'Jeep', 'Cherokee', 4, 'Grey', 'Automatic', '5 years old', TRUE, 'Petrol', 5, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEbytsFKcKGhYeL7VvblyPVU5hr8JBUuKKcC7qa_DFRMZuXOinIqFyBwB6NeaMgDWVdvI&usqp=CAU', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 50, 2016),
('3', 3, 'Tesla', 'Model 3', 4, 'White', 'Automatic', '2 years old', TRUE, 'Petrol', 5, 'https://upload.wikimedia.org/wikipedia/commons/9/91/2019_Tesla_Model_3_Performance_AWD_Front.jpg', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 190, 2019);
